<a href="https://colab.research.google.com/github/electiva1995-2026/etl-data-pipeline2513142020/blob/main/estudiante.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 29.0 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [2]:
from sqlalchemy import create_engine
import pandas as pd

In [3]:
database_url = "postgresql://etl_2513142020_user:6oodHwuJ6TmUgIzwtBJ9i9swhshYVjKZ@dpg-d6vhovf5gffc73dbaa4g-a.oregon-postgres.render.com/etl_2513142020"

In [4]:
engine = create_engine("postgresql://etl_2513142020_user:6oodHwuJ6TmUgIzwtBJ9i9swhshYVjKZ@dpg-d6vhovf5gffc73dbaa4g-a/etl_2513142020")
engine = create_engine("postgresql://etl_2513142020_user:6oodHwuJ6TmUgIzwtBJ9i9swhshYVjKZ@dpg-d6vhovf5gffc73dbaa4g-a.oregon-postgres.render.com/etl_2513142020")

In [5]:
test = pd.read_sql("SELECT 1", engine)

In [6]:
print(test)

   ?column?
0         1

In [8]:
import pandas as pd

url = "https://raw.githubusercontent.com/electiva1995-2026/etl-data-pipeline2513142020/refs/heads/main/data/raw/A_estudiantes.csv"

df = pd.read_csv(url)

df.head()

  id_estudiante             nombre edad                      correo
0         E1000         Raúl Gómez   26   carlos.castro45@correo.sv
1         E1001         Ana Castro   18  adriana.santos43@gmail.com
2         E1002   Ricardo Vásquez    23  maria.castro23@empresa.com
3         E1003        Sofía Gómez   27      luis.gomez77@correo.sv
4         E1004     Adriana Santos   26   elena.morales56@gmail.com

In [2]:
df.shape
df.columns
df.info()
df.isnull().sum()

NameError: name 'df' is not defined

In [10]:
estudiantes = df.copy()

estudiantes.columns = estudiantes.columns.str.strip().str.lower()

for col in estudiantes.select_dtypes(include='object').columns:
    estudiantes[col] = estudiantes[col].astype(str).str.strip()

estudiantes = estudiantes.replace(r'^\s*$', pd.NA, regex=True)

estudiantes['nombre'] = estudiantes['nombre'].str.lower()

# Si 'correo' es una dirección de correo electrónico, aplicar limpieza de texto, no de fecha.
estudiantes['correo'] = estudiantes['correo'].str.lower().str.strip()

estudiantes = estudiantes.drop_duplicates()

In [11]:
validos = estudiantes[
    estudiantes['nombre'].notna() &
    estudiantes['correo'].notna()
].copy()

rechazados = estudiantes[
    estudiantes['nombre'].isna() |
    estudiantes['correo'].isna()
].copy()

In [12]:
def motivo(row):

    motivos = []

    if pd.isna(row['nombre']):
        motivos.append("nombre_vacio")

    if pd.isna(row['correo']):
        motivos.append("correo_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [14]:
validos.to_csv("estudiantes_curated.csv", index=False)

rechazados.to_csv("estudiantes_rejects.csv", index=False)

In [15]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_2513142020_user:6oodHwuJ6TmUgIzwtBJ9i9swhshYVjKZ@dpg-d6vhovf5gffc73dbaa4g-a.oregon-postgres.render.com/etl_2513142020"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
   ?column?
0         1

In [21]:
validos.to_sql(
    'estudiantes_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'estudiantes_rejects',
    engine,
    if_exists='append',
    index=False
)

0

In [22]:
pd.read_sql(
"SELECT * FROM estudiantes_curated LIMIT 10",
engine
)

  id_estudiante            nombre edad                        correo
0         E1000        raúl gómez   26     carlos.castro45@correo.sv
1         E1001        ana castro   18    adriana.santos43@gmail.com
2         E1002   ricardo vásquez   23    maria.castro23@empresa.com
3         E1003       sofía gómez   27        luis.gomez77@correo.sv
4         E1004    adriana santos   26     elena.morales56@gmail.com
5         E1005      carlos pérez   26      diego.perez25empresa.com
6         E1006  valeria martínez   25      luis.romero1@outlook.com
7         E1007     ana hernández   22     elena.romero9@empresa.com
8         E1008    carmen vásquez   21   daniela.morales85@gmail.com
9         E1009      andrés mejía   20  natalia.rivera65@empresa.com