<a href="https://colab.research.google.com/github/electiva1995-2026/etl-data-pipeline2513142020/blob/main/notebooks/notas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 40.6 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [2]:
from sqlalchemy import create_engine
import pandas as pd

In [3]:
database_url = "postgresql://etl_2513142020_user:6oodHwuJ6TmUgIzwtBJ9i9swhshYVjKZ@dpg-d6vhovf5gffc73dbaa4g-a.oregon-postgres.render.com/etl_2513142020"

In [4]:
engine = create_engine("postgresql://etl_2513142020_user:6oodHwuJ6TmUgIzwtBJ9i9swhshYVjKZ@dpg-d6vhovf5gffc73dbaa4g-a/etl_2513142020")
engine = create_engine("postgresql://etl_2513142020_user:6oodHwuJ6TmUgIzwtBJ9i9swhshYVjKZ@dpg-d6vhovf5gffc73dbaa4g-a.oregon-postgres.render.com/etl_2513142020")

In [5]:

test = pd.read_sql("SELECT 1", engine)

In [6]:

print(test)

   ?column?
0         1

In [7]:
import pandas as pd

url = "https://raw.githubusercontent.com/electiva1995-2026/etl-data-pipeline2513142020/refs/heads/main/data/raw/A_notas.csv"

df = pd.read_csv(url)

df.head()

  id_nota id_estudiante id_curso nota  periodo
0   N5000         E1102     C204  7.9   I-2025
1   N5001         E1179     C205  8.1   I-2025
2   N5002         E1092     C202  8.6   I-2025
3   N5003         E1014     C211  8.0   I-2025
4   N5004         E1106     C208  7.4  II-2025

In [8]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_nota        330 non-null    object
 1   id_estudiante  325 non-null    object
 2   id_curso       328 non-null    object
 3   nota           326 non-null    object
 4   periodo        330 non-null    object
dtypes: object(5)
memory usage: 13.0+ KB

id_nota          0
id_estudiante    5
id_curso         2
nota             4
periodo          0
dtype: int64

In [9]:
notas = df.copy()

notas.columns = notas.columns.str.strip().str.lower()

for col in notas.select_dtypes(include='object').columns:
    notas[col] = notas[col].astype(str).str.strip()

notas = notas.replace(r'^\s*$', pd.NA, regex=True)

notas['id_estudiante'] = notas['id_estudiante'].str.lower()

notas['id_curso'] = notas['id_curso'].str.lower().str.strip()

notas = notas.drop_duplicates()

In [10]:

validos = notas[
    notas['id_estudiante'].notna() &
    notas['id_curso'].notna()
].copy()

rechazados = notas[
    notas['id_estudiante'].isna() |
    notas['id_curso'].isna()
].copy()

In [11]:
def motivo(row):

    motivos = []

    if pd.isna(row['id_estudiante']):
        motivos.append("id_estudiante_vacio")

    if pd.isna(row['id_curso']):
        motivos.append("id_curso_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [12]:
validos.to_csv("notas_curated.csv", index=False)

rechazados.to_csv("notas_rejects.csv", index=False)

In [13]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_2513142020_user:6oodHwuJ6TmUgIzwtBJ9i9swhshYVjKZ@dpg-d6vhovf5gffc73dbaa4g-a.oregon-postgres.render.com/etl_2513142020"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
   ?column?
0         1

In [14]:
validos.to_sql(
    'notas_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'notas_rejects',
    engine,
    if_exists='append',
    index=False
)

2

In [15]:

pd.read_sql(
"SELECT * FROM notas_curated LIMIT 10",
engine
)

  id_nota id_estudiante id_curso nota  periodo
0   N5000         e1102     c204  7.9   I-2025
1   N5001         e1179     c205  8.1   I-2025
2   N5002         e1092     c202  8.6   I-2025
3   N5003         e1014     c211  8.0   I-2025
4   N5004         e1106     c208  7.4  II-2025
5   N5005         e1071     c204  3.9  II-2025
6   N5006         e1020     c207  5.2  II-2025
7   N5007         e1102     c200  5.8   I-2025
8   N5008         e1121     c204  2.7   I-2025
9   N5009         e1074     c202  6.2   I-2025